version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestDocIssueProject
  gitServerName: test
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
- name: EmployeePayroll
  gitServerName: test
  gitUrl: https://github.com/rahul-singh-IBM-68
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
services:
- serviceName: project.testdocissue.integrations:FLOW_7046
  packages:
  - name: TestDocIssueProject
    version: "1.0"
