version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestDocIssueProject
  gitServerName: test
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
services:
- serviceName: project.testdocissue.integrations:test1
  packages:
  - name: TestDocIssueProject
    version: "1.0"
